name: lidar3
channels:
  - pytorch-lts
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _tflow_select
  - aiohttp
  - astor
  - astunparse
  - async-timeout
  - attrs
  - autopep8
  - blas
  - blinker
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - coverage
  - cryptography
  - cudatoolkit
  - cycler
  - cython
  - dataclasses
  - dbus
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freetype
  - gast
  - giflib
  - glib
  - gmp
  - gnutls
  - gst-plugins-base
  - gstreamer
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - intel-openmp
  - jax
  - jaxlib
  - jpeg
  - keras-preprocessing
  - kiwisolver
  - lame
  - lcms2
  - ld_impl_linux-64
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libidn2
  - libopus
  - libpng
  - libprotobuf
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libuv
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - llvm-openmp
  - lz4-c
  - markdown
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - multidict
  - munkres
  - ncurses
  - nettle
  - ninja
  - numexpr
  - oauthlib
  - olefile
  - openh264
  - openssl
  - opt_einsum
  - pandas
  - pcre
  - pillow
  - pip
  - protobuf
  - pthread-stubs
  - pyasn1
  - pyasn1-modules
  - pycodestyle
  - pycparser
  - pyemd
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytz
  - qt
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scipy
  - seaborn
  - setuptools
  - sip
  - sqlite
  - tensorboard-plugin-wit
  - tensorflow-estimator
  - termcolor
  - tk
  - toml
  - torchaudio
  - torchvision
  - tornado
  - typing-extensions
  - typing_extensions
  - urllib3
  - werkzeug
  - wheel
  - wrapt
  - x264
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yarl
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py
    - addict
    - anyio
    - argon2-cffi
    - backcall
    - bleach
    - clang
    - contextlib2
    - debugpy
    - defusedxml
    - deprecation
    - dill
    - dm-tree
    - entrypoints
    - flatbuffers
    - grpcio
    - h5py
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - joblib
    - json5
    - jsonschema
    - jupyter-client
    - jupyter-core
    - jupyter-packaging
    - jupyter-server
    - jupyterlab
    - jupyterlab-pygments
    - jupyterlab-server
    - jupyterlab-widgets
    - keras
    - markupsafe
    - matplotlib-inline
    - mistune
    - ml-collections
    - nbclassic
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - notebook
    - numpy
    - open3d
    - opencv-python
    - packaging
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - prometheus-client
    - promise
    - prompt-toolkit
    - ptyprocess
    - pygments
    - pyrsistent
    - pyyaml
    - pyzmq
    - requests-unixsocket
    - scikit-learn
    - send2trash
    - six
    - sniffio
    - tensorboard
    - tensorboard-data-server
    - tensorflow
    - tensorflow-addons
    - tensorflow-datasets
    - tensorflow-gan
    - tensorflow-hub
    - tensorflow-io
    - tensorflow-io-gcs-filesystem
    - tensorflow-metadata
    - tensorflow-probability
    - terminado
    - testpath
    - threadpoolctl
    - tomlkit
    - torch-tb-profiler
    - traitlets
    - typeguard
    - wcwidth
    - webencodings
    - websocket-client
    - widgetsnbextension
